#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f /usr/sbin/openvpn ] && \
[ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    iproute2 \
    openvpn 
fi
if [ ! -f /usr/sbin/openvpn ] && \
[ -f /sbin/apk ]; then
  # Alpine
  apk add --no-cache \
    iproute2 \
    openvpn 
fi

echo tun >> /etc/modules
mkdir -p /dev/net
mknod /dev/net/tun c 10 200 &> null
chmod 600 /dev/net/tun

chown -R root:root /root